# Generated by Django 2.2.19 on 2021-11-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='criteria',
            field=models.FloatField(null=True),
        ),
    ]
