# Generated by Django 2.2.19 on 2021-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_portfolio_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='criteria',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
